apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-store
  labels:
    app: image-store
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-store
  template:
    metadata:
      labels:
        app: image-store
    spec:
      containers:
      - name: image-store
        image: imgstore:dev
        ports:
        - containerPort: 8080
