apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql-ha
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql-ha
  version: 16.0.5
  targetNamespace: development
  createNamespace: true
  valuesContent: |-
    global:
      postgresql:
        password: "postgres"
        database: "postgres"
        username: "postgres"
      security:
        allowInsecureImages: true
    persistence:
      storageClass: local-path
    postgresql:
      image:
        registry: ghcr.io
        repository: sofushn/ruc-workshop-dds-project
        tag: database-latest
      replicaCount: 3
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
    pgpool:
      replicaCount: 1
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
