apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-store-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
