apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: ghcr.io/sofushn/ruc-workshop-dds-project:website-latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
